PRESS0-1723: WP Admin | Branded Plugin | Solutions Entitlements Page
newfold-labs/wp-module-solutions pull request #11
Opened 2024-10-08 16:09 UTC by aratidgr8

## Proposed changes

My plugins & tools page as per [JIRA](https://jira.newfold.com/browse/PRESS0-1723)

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Video

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] I have viewed my change in a web-browser
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-10-08 22:38 UTC, wpscholar requested changes
@aratidgr8 - Can you make sure we add the data attributes for PLS to handle installing any relevant plugins?

2024-10-09 00:09 UTC, circlecube commented
@aratidgr8 I loaded this up locally, it's looking really good. One thing I noticed is all the accordions open and close together, ideally each should be individually controlled.

I am going to merge this PR for now to keep our latest in each dev release, can you work on that and the PLS logic similar to what is in the plugin script for installing/pls/activating these entitlements here: https://github.com/newfold-labs/wp-module-solutions/blob/main/includes/js/myPluginsTools.js#L56-L68 

Thanks!

2024-10-09 00:09 UTC, circlecube approved these changes

2024-10-09 00:10 UTC, merged

2024-10-09 13:57 UTC, aratidgr8 commented
@circlecube  / @wpscholar 
Hi,

- Data attributes for PLS added
- Accordians open & collapse fixed

Changes are in this [PR](https://github.com/newfold-labs/wp-module-solutions/pull/13)